### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by dhruvilxcode** [dhruvilxcode/ineuron-landing-page#1]
- [x] Create video
- [x] Make repo Public
- [x] Improve Readme, add more details, and process
- [x] Publish to Findcoder.io
- [x] sub-me
